### ISSUE TITLE
SirLuthor's Tools crashes mlox

### ISSUE THREAD

**Issue by Dragon-32** [mlox/mlox#14]
Originally brought to my attention over on [Nexus](https://forums.nexusmods.com/index.php?/topic/1314413-mlox/?p=52771858) where you can also read my no doubt embarrassing attempts to decipher what's going on.

When I activate "SirLuthor-Tools.esp" and launch mlox I get the following fatal error message:

> mlox.py 0.61 [mlox-base 2017-08-02 15:53:33 (UTC)] (en/cp1252)
> Python Version: 2.7
> wxPython Version: 3.0.2.0
> 
> Traceback (most recent call last):
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 1891, in <module>
>     main()
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 1799, in main
>     mlox_gui().start()
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 1638, in start
>     self.analyze_loadorder(None)
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 1619, in analyze_loadorder
>     lo = loadorder().update(fromfile)
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 1338, in update
>     if not parser.read_rules("mlox_base.txt", progress):
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 880, in read_rules
>     self.parse_statement(self.curr_rule, new_rule.group(2), new_rule.group(3))
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 774, in parse_statement
>     (bool, expr) = self.parse_expression()
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 684, in parse_expression
>     return(self.parse_desc())
>   File "C:\Games\Bethesda Softworks\Morrowind\mlox\mlox.py", line 605, in parse_desc
>     re_pat = re.compile(pat)
>   File "C:\Python27\lib\re.py", line 194, in compile
>     return _compile(pattern, flags)
>   File "C:\Python27\lib\re.py", line 251, in _compile
>     raise error, v # invalid expression
> error: nothing to repeat

Mod can be downloaded here - http://mw.modhistory.com/download--5937

This is caused by rules (added by me) which use the DESC predicate like this:
```[DESC !/*Edited by Tooplex for MGSO Compatibility*/ SirLuthor-Tools.esp]```

The asterisks throw off the regular expression, changing the check to this fixes it:
```[DESC !/Tooplex/ SirLuthor-Tools.esp]```

Need to change the various rules added and not use asterisks in the future.

**Comment by Dragon-32** [comment]
Fixed in latest mlox rule-set
