### ISSUE TITLE
Error with mlox 0.62

### ISSUE THREAD

**Issue by MosAnted** [mlox/mlox#19]
Just updated to 0.62 from 0.61, and I'm getting the following error message when trying to run it:

mlox.exe 0.62 (es_MX/cp1252)
Python Version: 2.7
wxPython Version: 3.0.2.0

Traceback (most recent call last):
  File "D:\Steam\steamapps\common\Morrowind\mlox\mlox.py", line 250, in <module>
  File "D:\Steam\steamapps\common\Morrowind\mlox\modules\gui.py", line 322, in start
  File "D:\Steam\steamapps\common\Morrowind\mlox\modules\gui.py", line 316, in analyze_loadorder
  File "D:\Steam\steamapps\common\Morrowind\mlox\modules\gui.py", line 281, in display
  File "C:\Python27\lib\StringIO.py", line 271, in getvalue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 111: ordinal not in range(128)

**Comment by imset** [comment]
Getting almost the exact same error:

mlox.exe 0.62 (en_US/cp932)
Python Version: 2.7
wxPython Version: 3.0.2.0

Traceback (most recent call last):
  File "C:\GOG Games\Morrowind\mlox\mlox.py", line 250, in <module>
  File "C:\GOG Games\Morrowind\mlox\modules\gui.py", line 322, in start
  File "C:\GOG Games\Morrowind\mlox\modules\gui.py", line 316, in analyze_loadorder
  File "C:\GOG Games\Morrowind\mlox\modules\gui.py", line 281, in display
  File "C:\Python27\lib\StringIO.py", line 271, in getvalue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 98: ordinal not in range(128)

I got the same error with mlox 0.61 as well. I thought updating it would fix it, but no dice.

**Comment by EmperorArthur** [comment]
Looks like it was a unicode issue I missed in testing.

Do any of the mods you're using have any non English Characters?  We now attempt to use the proper characters instead of sticking to purely English (ascii) ones.

I'll upload a pure ascii `mlox_base.txt` here later today or tomorrow.  If that fixes the problem, then I can work on solving it for future builds.

**Comment by EmperorArthur** [comment]
Here's a file that potentially fixes the issue.  [mlox_base.txt](https://github.com/mlox/mlox/files/1332062/mlox_base.txt)

If it does or doesn't, I'd appreciate you sending me Mlox's generated mod list.

**Comment by imset** [comment]
That worked, thank you.
I'm assuming you mean the current_loadorder.out file?
If so, here's mine:

```
Morrowind.esm
Tribunal.esm
Bloodmoon.esm
Patch for Purists v2.2.esm
Morrowind Patch v1.6.4.esm
Better Heads.esm
Tamriel_Data.esm
Better Heads Tribunal addon.esm
Better Heads Bloodmoon addon.esm
TR_Mainland.esm
entertainers.esp
bcsounds.esp
LeFemmArmor.esp
EBQ_Artifact.esp
Siege at Firemoth.esp
Clear Your Name.esp
NON2.RoadtoMournhold.v1.0.2a.esp
Better Bodies.esp
Better Clothes_v1.1.esp
New Argonian Bodies - Mature.esp
New Khajiit Bodies - Mature.esp
TR_Mainland_1612Patch.ESP
```

I'm new to Morrowind modding, so all my mods are from things like STEP and other guides.

**Comment by Alignn** [comment]
After doing a clean reinstall of MW for unrelated reasons I got this bug when just using the base game + Trib/BM, but the new .txt file fixed the issue for me as well. Thanks!

Might be worth mentioning that my OS' language is Swedish rather than English, so characters like åäö may be related to the issue? I noticed the cmd window for some reason says "Hallå" at the end of the line with mlox's version.

**Comment by imset** [comment]
My system language is English, but sets non-unicode characters to Japanese. So that could definitely be related.

**Comment by EmperorArthur** [comment]
If you're familiar with the command prompt, could any of you run `mlox -n` and see if it works.

I've recently changed systems and am seeing this behavior myself with the GUI, so it is being worked on.

**Comment by Alignn** [comment]
mlox -n seems to run, it outputs a proposed load order and all the usual stuff, despite an error:

`INFO (root): mlox 0.62 Hallå[0m
INFO (mlox.loadorder): Found 91 plugins in: "C:\Spel\Morrowind\Morrowind.ini"[0m
[0;30;41mERROR (mlox.parser): C:\Spel\Morrowind\mlox\mlox_base.txt:1: Parse Error(), expected start of rule [Buffer=﻿;; -*- mode: emacs-lisp -*-][0m
INFO (mlox.parser): "mlox_base.txt" Version  2017-00-09 20:16:28 (UTC)[0m
INFO (mlox.parser): Read 7735 rules from: "C:\Spel\Morrowind\mlox\mlox_base.txt"[0m
INFO (mlox.loadorder): [Plugins already in sorted order. No sorting needed!][0m
INFO (mlox.loadorder): current saved to: current_loadorder.out[0m
INFO (mlox.loadorder): mlox sorted saved to: mlox_new_loadorder.out[0m
`

(Plugin info and load order omitted)

**Comment by EmperorArthur** [comment]
Hmm, the strange part for me is all the `�`.  Those should all be returns, but aparently the compiled version isn't working correctly.  That's a separate issue though.

'Parse Error(), expected start of rule [Buffer=﻿;; -*- mode: emacs-lisp -*-]' is something that can be ignored.  It's the parsing thinking the line to tell the text editor something is actually a rule, when it's not.

Was that `mlox -n` run with the `mlox_base.txt` posted here or the original.  If you could try it with the original, I'd appreciate it.  If it doesn't crash, then I'll know it's the GUI instead of just suspecting it.

**Comment by Alignn** [comment]
That was with the original mlox_base.txt, the new one is the same except it doesn't produce the parse error (and works without -n).

**Comment by EmperorArthur** [comment]
Thanks.  I realized what was causing that problem, and opened issue #21.

This is a high priority issue, and I'm slowly slogging through getting it fixed.  I'll be posting some pre-release binaries to make sure that 0.63 works properly.
