### ISSUE TITLE
Wrye Mash 87 (or higher) Support

### ISSUE THREAD

**Issue by Sharlikran** [mlox/mlox#20]
I have been fiddling with things. The master branch is in shambles so please don't criticize.  I will have a fully rebased branch by next week or sooner.

Currently I am looking to see what I can update and whether or not I broke anything. I have a [standalone EXE](https://github.com/Wrye-Bashers/Wrye-Mash/releases/tag/87) I have given to Leonardo on [AFK Mods](https://afkmods.iguanadons.net/index.php?/topic/5068-wipz-wrye-mash/).

I have imported most of the Wrye Bash code. Anything that was similar to what Wrye, Yacoby, or Melchor had originally.  As long as I thought wouldn't break the code.  What that has done is given the foundation to Wrye Mash to have more Unicode support. However, unfortunately it's made the code less easy to  work with for me.  So if I want to simply check if `mlox.exe` exists I don't know how to use the updated `def GPath` or `class Path` because it returns unicode now and `os.path.exists()` will complain.

Not sure if you can understand the code changes and like I said I have to finish fully rebasing a lot more.  I thought I'd let you know I was working on it and see what you thought. Don't worry about helping rebase because I have something I'm doing and I want it to be a specific way. Then I'll make proper commits. I'm not perfect when it comes to commits but when I am done it should be cleaner.

It's set up to work with 2.7.12 and (crossing my finders) WxPython 2.8.12.1 Unicode. If it could be updated to 4.0 after I am done rebasing things that would be fine with me. Until I'm done rebaseing it wouldn't make much sense to work on it though since the code will change. 

This is just meant to be more informative then an actual issue.

Previously the code from Yacoby imported things in an odd way.  There would even be things like `bush = mush` and `bosh = mosh`. I have cleaned up most of the imports but I haven't removed all of the `import module` followed by `from module import stuff` references.  Because of this your Python code won't work now.  I had an error during testing that there was no `dir` attribute.

```Python
mlox.exe 0.62 (en_US/cp1252)
Python Version: 2.7
wxPython Version: 3.0.2.0

Traceback (most recent call last):
  File "D:\Wrye-Mash\Mopy\mash\mlox\mlox.py", line 250, in <module>
    if args.gui or noargs:
  File "D:\Wrye-Mash\Mopy\mash\mlox\modules\gui.py", line 322, in start
    self.analyze_loadorder(None)
  File "D:\Wrye-Mash\Mopy\mash\mlox\modules\gui.py", line 296, in analyze_loadorder
    self.lo = loadorder()
  File "D:\Wrye-Mash\Mopy\mash\mlox\modules\loadOrder.py", line 31, in __init__
    self.game_type, self.plugin_file, self.datadir = fileFinder.find_game_dirs()
  File "D:\Wrye-Mash\Mopy\mash\mlox\modules\fileFinder.py", line 174, in find_game_dirs
    file_logger.debug("Data Files at: {0}".format(datadir.dirpath()))
  File "D:\Wrye-Mash\Mopy\mash\mlox\modules\fileFinder.py", line 72, in dirpath
    return(self.dir)
AttributeError: caseless_dirlist instance has no attribute 'dir'
```

also my testing what done using the following types of imports:
```Python
from mash.mlox.modules.loadOrder import loadorder
from mash.mlox.modules.gui import load_translations
```
altering resources.py
```
program_path = os.path.realpath(sys.path[0]) <<-- changed to point to the mopy mash folder
resources_path = os.path.join(program_path,"Resources") <<-- changed to point to the mopy mash folder
```
I just printed sys.path to see where I was and added the proper addition like `'mash\\mlox'` or whatever it was. I lost the changes doing a cleanup so I could test.

I am able to use mlox 61 with Mrye Mash 87 as long as I copy the mlox.py file from `For users of Wrye Mash Standalone`. Thanks for including that.

**Comment by Sharlikran** [comment]
@EmperorArthur @Dragon-32 Sorry I know this isn't really a forum, but wasn't sure how to get ahold of you two. We can chat more at AFK mods.

**Comment by EmperorArthur** [comment]
Hi,

It's really neat that you're working on integrating newer versions of mlox into Wrye-Bash.

mlox is currently in flux.  I'll see what I can do to clean up the documentation, but there are a few things you should be aware of.

First, the internal interface is still in flux.  Probably the best way to integrate mlox into your program is via the command line.  I'd be happy to work with you on creating an appropriate api, so mlox can give you data that way.  Something like `mlox --data-dir 'C:\...' --messages-out-file file_name.txt --sorted-file sorted_list.txt`.

Next, I'm working on moving to python3.  Unicode is currently causing issues on some platforms, so I'd like to move to a platform that handles it more cleanly.  Plus, I think the new pathlib shows promise.  This would cause major issues for you if you use the modules directly.

I'm also working on more closely following the Python naming convention.  I'm 90% sure that the 'modules' directory should also be named 'mlox'.  I'll see what I can do to keep the source directory

**Comment by Sharlikran** [comment]
I probably won't understand the git stuff because I'm pretty new to Git. Python, I just started teaching myself Python a few weeks ago. I have used Basic, Lua, Pascal/Delphi, and Python over the years since high school, just never really learned everything about them to be able to use them properly and effectively.

As far as Python 3 goes, yes I would like to get Wrye Mash to work with Python 3 also. I have more work to do but the other day digging through the code there were various exceptions, a class named PickleDict, and two classes for log files. Duplicated in two files and inheriting themselves somehow.  None of which was needed. I am hoping that once I am done finding all the things like that, that Wrye Mash will have much less code and will be easier to port to Python 3.

Since I don't know Python that well yet it might be a bit of a struggle. So for now I'm just getting familiar with Wrye Mash code, familiar with Python itself, and trying to be able make changes that don't break something. I have always just cut and pasted things or if I am using existing code I can see how it's done and duplicate that. More or less I can manipulate code, I can't write it.

I had added much of the code I thought would work with Wrye Mash from the main Wrye Bash project like I said, but adding that much code made it start complaining that comparisons could not be evaluated since one was unicode and the other wasn't.  So I didn't really break it but now I'm forced to update the rest to be unicode as well. So it will take a lot of work.

Also as far as naming conventions go. Since I am new I don't fully understand Pep 8 or most of the PEP documents. However, if the name space is mash.mlox.mlox.loadorder then that would seem a bit much to me where as mash.mlox.modules.loadorder makes a bit more sense.  

Although even that was confusing to figure out for me because I'm new.  While trying to remove the workarounds I found left over from all three authors, it was hard to understand why Python complained about what it was importing.  Eventually I figured it out that I had to change most of the mlox code to work from mash as I mentioned above. I'm going to be guilty of using packages soon, but a flatter name space would be nice.

On the subject of classes and name spaces, I have been watching videos about Python since I'm new and I came across one that I though was interesting titled [Stop Writing Classes](https://www.youtube.com/watch?v=o9pEzgHorH0).

**Comment by Sharlikran** [comment]
@EmperorArthur I have been able to update most of Wrye Mash to use Python 2.7.8 or higher, although I am currently using 2.7.14. I have also updated most of the code to have Unicode support. So for example a user named Leonardo has been testing this and he has a Sweedish version of windows. So with wxPython Unicode 2.8.12.1 he is able to use Wrye Mash. I have updated things when he reports an error reading INI files and whatever. So most of the more important updates are finished. I feel that mostly I just have to find all the strings like `_('Some Text To Print')` and change it to `_(u'Some Text To Print')` which that for the most part is just tedious and time consuming.

What I have run into is the following error `mlox_base.txt:1: Parse Error(), expected start of rule [Buffer=ï»¿;; -*- mode: emacs-lisp -*-]` because now that the environment has enough Unicode, the rules file is being opened as a Unicode file.

I don't think this has to happen. I'm not suggesting you use ConfigParser but I want to sue it as an example. With ConfigParser I can use this code to open a file.
```Python
mashIni = ConfigParser.SafeConfigParser()
with codecs.open('SomeFile.ini', 'r', encoding='utf-8') as f:
    mashIni.readfp(f)
```
If I do that then I can open a file and if it has Unicode in it then it will be read properly including lines with extended chars.

Somewhere in the mlox.py that you have packaged in the folder `For users of Wrye Mash Standalone`, the code is opening the rules file without any encoding. I feel it could be opened with something like cp1252 and then the error may not happen.  So again, I'll use my above example.
```Python
mashIni = ConfigParser.SafeConfigParser()
with codecs.open('SomeFile.ini', 'r', encoding='cp1252 ') as f:
    mashIni.readfp(f)
```
If I used that then SomeFile.ini would open and it would be more or less, ANSI. So nothing would have to change with your program, or the rules file that mlox.exe downloads.  What I am asking for help with is to change the mlox.py in `For users of Wrye Mash Standalone` to force opening the rules file with the cp1252 or some other kind of ANSI encoding so that even someone using a Unicode version of Wrye Mash won't get any errors like `mlox_base.txt:1: Parse Error(), expected start of rule [Buffer=ï»¿;; -*- mode: emacs-lisp -*-]`.

Is there any way you could help me with that I don't know python well enough to do it. I just started teaching myself about a month ago and I'm looking through your code and I'm just not seeing what I could change so the rules file is forced to open in cp1252 or ASNI or whatever.

**Comment by EmperorArthur** [comment]
See issue #18.  The new version of mlox_base.txt released today fixed it.  The problem wasn't really unicode, as it was a Byte Order Marker at the start of the file causing problems.

Please be aware that mlox is now a Python3 program as of this morning.  While in theory, 90% of the code should still work with Python 2.7, I know that RuleParser at least will not.  Also, it's now using Python3 print statements without the `from future import ...`

Currently mlox's two largest weaknesses are that we still don't support OpenMW and that we aren't using anything like `ConfigParser` anywhere in our code.  ConfigHandler will probably be converted to ConfigParser for Morrowind.ini at least.  However, any change to the rules file will require a strong break with old versions. I'm looking at the feasibility of converting the rules to XML, and using a format like that.

**Comment by Sharlikran** [comment]
I'll play around with Wrye Mash then and using it with the Utilities tab because I won't be able to update Wrye Mash to Python 3 until I learn more Python. I might disable the ability to run Mlox directly from Wyre Mash and force using it as an external program which I am sure will still work and sort the files just fine. I think at worst people will just request it as a feature and I'll have to keep explaining that until I can update Wrye Mash to Python 3 then it's not possible yet.

Thanks for the info I appreciate it.
