### ISSUE TITLE
at script/tes3cmd.pl line 7942.

### ISSUE THREAD

**Issue by staticnation** [mlox/mlox#33]
Traceback (most recent call last):
File "mash\masher.pyo", line 4064, in Mods_Tes3cmd_Fixit
File "mash\masher.pyo", line 7524, in Execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0x98 in position 0: ordinal not in range(128)

-----

FATAL ERROR (True_Lights_And_Darkness_1.0-NoDaylight.esp): no mast subtype: AMBI (id=ald-ruhn, arobar manor bedrooms) DUMP=$VAR1 = bless( {
'_recbuf_' => 'NAME Ald-ruhn, Arobar Manor Bedrooms DATAP(@?NAM0˜',
'_rectype_' => 'CELL',
'SH' => {
'NAME' => [
bless( {
'_subbuf_' => 'Ald-ruhn, Arobar Manor Bedrooms ',
'name' => 'Ald-ruhn, Arobar Manor Bedrooms',
'_id_' => undef
}, 'CELL::NAME' )
],
'NAM0' => [
bless( {
'reference_count' => 152,
'_subbuf_' => '˜',
'_id_' => undef
}, 'CELL::NAM0' )
],
'DATA' => [
bless( {
'flags' => 5,
'_id_' => undef,
'fog_density' => '0.75',
'_subbuf_' => 'P(@?',
'unknown' => 1321040
}, 'CELL::DATA' )
]
},
'_is_interior_' => 1,
'_hdrflags_' => 0,
'SL' => [
$VAR1->{'SH'}{'NAME'}[0],
$VAR1->{'SH'}{'DATA'}[0],
$VAR1->{'SH'}{'NAM0'}[0]
]
}, 'CELL' );
at script/tes3cmd.pl line 7942.

https://cdn.discordapp.com/attachments/381219559094616064/481301714851332096/True_Lights_And_Darkness_1.0-NoDaylight.esp

**Comment by staticnation** [comment]
wrong repo ment for tes3cmd
