### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)

### ISSUE THREAD

**Issue by staticnation** [mlox/mlox#34]
mlox.exe 0.62 (en_US/cp1252)
Python Version: 2.7
wxPython Version: 3.0.2.0

Traceback (most recent call last):
  File "C:\Games\Bethesda Softworks\Morrowind\Mlox\modules\gui.py", line 409, in menu_debug_handler
  File "C:\Python27\lib\StringIO.py", line 271, in getvalue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)

**Comment by EmperorArthur** [comment]
This should be fixed in the latest [release](https://github.com/mlox/mlox/releases/tag/v1.0).
