### ISSUE TITLE
Mlox keeps giving me this error message when I try to update my load order.

### ISSUE THREAD

**Issue by OOFLeelee** [mlox/mlox#49]
mlox.exe 0.61 [mlox-base 2017-00-09 20:16:28 (UTC)] (en/cp1252)
Python Version: 2.7
wxPython Version: 2.8.12.1

Traceback (most recent call last):
  File "mlox.py", line 1653, in on_update
  File "mlox.py", line 1619, in analyze_loadorder
  File "mlox.py", line 1379, in update
  File "mlox.py", line 1276, in update_mod_times
WindowsError: [Error 87] The parameter is incorrect

Morrowind Patch v1.6.6_beta.esm
Havish.esm
Aduls_Master_Mod.esm
Rise of House Telvanni.esm
Tamriel_Data.esm
TR_Mainland.esm
Sky_Main.esm
Cyrodiil_Main.esm
Morrowind Patch Project v1.6.6 [For Rebirth].esm
VSW_Tomb_of_the_Snow_Prince.esm
Bloodmoon.esm
Morrowind.esm
Tribunal.esm
FreeTheSlaves!.ESP
Uvirith's Legacy_3.53.esp
Unique_CaveRats.ESP
TheCityOfBalmora1.esp
LGNPC_Merged_Lt.esp
Expansion Delay.ESP
BM-Fixes.esp
Better Bodies.esp
DB_Attack_Mod.esp
Improved Inns.esp
abotTRWaterSound1912.esp
Quick Char.esp
Better Clothes_v1.1_nac.esp
Missing snow armor.esp
Aduls_Arsenal.esp
Tree replacer for TR.ESP
Building Up Uvirith's Legacy1.1.ESP
RoHT Havish Patch.esp
UL v2.0 RoHT v1.52 Compatibility.esp
Close Inspection.esp
Ownership Indicator.esp
Time Display.esp
Rebirth-- Combined.ESP
Companion Health Bars.esp
Vampiric Hunger UI (MGE XE).esp
TR_Factions.esp
TR_Preview.esp
TR_Travels_(Preview_and_Mainland).esp
TR_OldTravels.esp
ReBirthGrassv02.esp
BlightedAnimalsRetextured.esp
TR_travel.esp
Azure_grass.esp
Azure_isle.esp
TR_Azure_upd.esp
Azure_isle_leveled.esp
ingridient_forest.esp
LowerFirstPersonSneak.ESP
Smart_Crosshair.esp
TR Improved Inns Add-on.ESP
Shrines - Restore Health and Cancel Options.esp
Distant Thunder.ESP
Flies.ESP
The City of Ald-ruhn v1.esp
Cave Drips.ESP
MDP 2016.esp
Mountains_of_Mournhold_V3.5.esp
Balmora Expansion v1.5.esp
Cyrodiil_Grass.ESP
Visible Temple.esp
Shattered Stones - An Earthquake Mod.esp
2pacBetterClothes.ESP
2pacExtraConversions.ESP
Tamriel Rebuilt Vurts Leafy West Gash Tree Fix.ESP
Grass-TR.esp
Julan Ashlander Companion 2.02 [For Rebirth].esp
tribunal rebalance.ESP
TR_StrangledFen.ESP
GITD_Telvanni_Dormers_Exterior.ESP
RR_Windoors_Glow_1C.esp
GITD_Telvanni_Dormers_Interiors.ESP
GITD_Telvanni_Dormers.ESP
Solstheim TotSP [For Rebirth].esp
Grass for Morrowind Rebirth 4.7.1.esp
Morrowind Rebirth - Mercenaries [Addon].ESP
Morrowind Rebirth - Skills [Addon].ESP
Morrowind Rebirth - Races [Addon].esp
Morrowind Rebirth - Tools [Addon].ESP
Morrowind Rebirth - Birthsigns [Addon].ESP
Morrowind Rebirth - Game Settings [Addon].ESP
Better Landscapes 2.4.3.esp
Bottles.esp
TR_Heads_Unlocked.esp
Animated Rebirth.ESP
Fixed-Rebirth-Balmora.ESP
Labeled_roadsigns_TR.ESP
GH_TestCell_TR.esp
Beware the Sixth House.ESP
GH_trama_patch.esp
Unique Tavern Signs for Tamriel Rebuilt.ESP
XE Sky Variations.esp
GrassRebirth2.esp
GrassRebirth1.esp
Snow Prince Armor Redux.ESP
Siege at Firemoth [For Rebirth].esp
VSW-Rem-Anthology Solstheim.esp
Morrowind Rebirth [Main].ESP
GITD_WL_RR_Interiors.esp
Yet Another Guard Diversity - Imperial.ESP
Yet Another Guard Diversity - Hlaalu.ESP
Yet Another Guard Diversity - Redoran.ESP
Yet Another Guard Diversity - Ordinator.ESP
Yet Another Guard Diversity - Telvanni (Full Cephalopod).ESP
Bloodmoon Rebalance.esp
Morrowind Rebirth [TR].ESP
TheBareNecessities.esp
Yet Another Guard Diversity - Bloodmoon.ESP
VSW_TOTSP_TR_Preview.esp
VSW_TOTSP_abotBoats.esp
VSW_Anthology_Doors_of_Oblivion_Patch.ESP
VSW_Solstheim_TD_Item_Expansion.esp
@Arm_patch(EN).esp
TR Vermai on Vvardenfell.esp
TR_TransportLinks.ESP
Yet Another Guard Diversity - TR.ESP
@_BM_Patch_v1.7(EN).esp
@_BM_legionSnowArmor(En).esp
@_BM_riverGuards(EN).esp
@_GuarFix(EN).esp
@_SuiteLite_v1.7(en).esp
@_Symphony_the_v1.7(En)Compatible.esp
@_arrowSpeed(All).esp
@_effct(EN).esp
@_imperial_forts(En).esp
Mashed Lists.esp

**Comment by cpassuel** [comment]
Propably a little late, this issue is related to FAT32 file system. See https://github.com/mlox/mlox/issues/57 for more info
