### ISSUE TITLE
Help: mlox update load order error

### ISSUE THREAD

**Issue by GKA2000** [mlox/mlox#57]
Hello,

I have both Morrowind and mlox installed on an external hard drive. I'm experiencing a problem with mlox ver 1.0.3 where whenever I try to use the Update Load Order function, I get the following error message:
```
mlox.exe 1.0.3 (en_US/cp1252)
PyQt5: Version: 5.13.0
appdirs: Version: 1.4.3
py7zr: Installed
libarchive: Not Installed
7-Zip: Not Installed

Traceback (most recent call last):
  File "mlox\qtGui.py", line 269, in commit
  File "mlox\loadOrder.py", line 250, in write_new_order
  File "mlox\configHandler.py", line 260, in write
OSError: [WinError 87] The parameter is incorrect
```
This has been tested with a clean install, through MO2, and through Wrye Mash all with the same result. I have no clue what steps to take to resolve this error.

**Comment by cpassuel** [comment]
I have the same issue, I have found this post about it https://www.reddit.com/r/tes3mods/comments/s1oert/help_with_mlox/
It seems to be related to the type of drive (fixed vs removable)
I'm installing Morrowind on a ram disk to test different mods

On other post this error message seems to be related to a bug in specific version of Python

**Comment by cpassuel** [comment]
I ran the python code and the problem comes from the os.utime(**filename**, (-1, mtime)) statements (lines 260, 263, 266 and 269 of configHandler.py).

Apparently on certain type of drive you cannot set access time to -1.
I'm not really sure what's the use of setting access time to -1 but you can probably set it to a date before the launch of Morrowind like 946682906 (around 1st January of 2000)

**Comment by cpassuel** [comment]
After further investigation, the error is related to the minimal date a file sytem supports : For NTFS it's 1st January of 1970 and for FAT32 it's 1st January of 1980.
So a safe value for both FS is 315529200 (01/01/1980) or more instead of -1 in os.utime(filename, (-1, mtime)) statements

**Comment by WinterStrike** [comment]
I am having this very same issue.  How do I go about fixing this? I'm not quite sure I understand the above comments. Am I changing a piece of code?

**Comment by Sneaks911** [comment]
I am receiving the same error, but with additional lines in the error report. I am Using OpenMW and running Mlox through MO2/OpenMW

mlox.exe 1.0.3 (en_US/cp1252)
PyQt5: Version: 5.13.0
appdirs: Version: 1.4.3
py7zr: Installed
libarchive: Not Installed
7-Zip: Not Installed

Traceback (most recent call last):
  File "mlox\qtGui.py", line 269, in commit
    self.lo.write_new_order()
  File "mlox\loadOrder.py", line 250, in write_new_order
    if configHandler.dataDirHandler(self.datadir).write(self.new_order):
  File "mlox\configHandler.py", line 260, in write
    os.utime(self._full_path("Morrowind.bsa"), (-1, mtime))
OSError: [WinError 87] The parameter is incorrect

**Comment by cpassuel** [comment]
> I am having this very same issue. How do I go about fixing this? I'm not quite sure I understand the above comments. Am I changing a piece of code?

Yes there is a bit of code to change, but you'll have to compile it. Check my release rather https://github.com/cpassuel/mlox/releases/tag/v1.04

**Comment by cpassuel** [comment]
> I am receiving the same error, but with additional lines in the error report. I am Using OpenMW and running Mlox through MO2/OpenMW
> 
> mlox.exe 1.0.3 (en_US/cp1252) PyQt5: Version: 5.13.0 appdirs: Version: 1.4.3 py7zr: Installed libarchive: Not Installed 7-Zip: Not Installed
> 
> Traceback (most recent call last): File "mlox\qtGui.py", line 269, in commit self.lo.write_new_order() File "mlox\loadOrder.py", line 250, in write_new_order if configHandler.dataDirHandler(self.datadir).write(self.new_order): File "mlox\configHandler.py", line 260, in write os.utime(self._full_path("Morrowind.bsa"), (-1, mtime)) OSError: [WinError 87] The parameter is incorrect

Not sure about the mlox version used in OpenMW but you can try my release https://github.com/cpassuel/mlox/releases/tag/v1.04

**Comment by Sneaks911** [comment]
**Not sure about the mlox version used in OpenMW but you can try my release https://github.com/cpassuel/mlox/releases/tag/v1.04**   

That works perfectly.  Thank you!
